- README.md
> chore: readme template

- app/Http/Controllers/Controller.php
- app/Http/Controllers/ProfileController.php
- public/index.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/header.blade.php
- resources/views/layouts/navigation.blade.php
- routes/web.php
> Change customer info

- .env.example
- README.md
- package-lock.json
- package.json
- Change the default `APP_NAME` in `.env.example`.
- Add Xdebug configuration to `.env.example`.
- Change the ip addresses to hostnames in `.env.example`.
- Clarify/correct some things in the README.
- Add an explicit name to `package.json` so it's not changed to the branch name every time.
> Small general cleanup.

- README.md
- Add information on how to apply code style with Laravel Pint.
- Fix the interpreted HTML in the general section at the bottom.
- Remove the 'TEST' after the title.
> Fix up some things in the README.

- resources/views/add_employee.blade.php
- resources/views/dashboard.blade.php
- resources/views/dashboard/my_pickups.blade.php
- resources/views/employee_view.blade.php
- resources/views/layouts/guest.blade.php
- resources/views/layouts/header.blade.php
- resources/views/livewire/create-pickup-form.blade.php
- resources/views/livewire/my-pickups-list.blade.php
- routes/web.php
- Fix routes that broke after refactoring `routes/web.php`.
- Change Blade templates over to use `route()` instead of hardcoded routes.
> Fix broken routes and switch to route names.

- database/README.md
- database/migrations/2023_04_01_100723_big_update.php
- routes/web.php
The database schema has been reworked on 30-03-2023. This PR combines the work to move the project to the new version of the schema.
> Add migrations for updated database schema.

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/UserController.php
- app/Http/Kernel.php
- app/Models/Employee.php
- app/Models/User.php
- app/Providers/AuthServiceProvider.php
- app/Providers/EloquentUserProvider.php
- config/auth.php
- database/migrations/2023_03_29_143659_users_add_soft_deletion.php
Add soft deletion for users and employees so they aren't completely gone upon deletion, causing inconsistencies in the database.
> Add soft deletion to users and employees.

- .bladeformatterrc.json
- resources/views/customers.blade.php
- resources/views/customers_edit.blade.php
- resources/views/layouts/header.blade.php
- resources/views/layouts/navigation.blade.php
- resources/views/overview.blade.php
- resources/views/shipments/create.blade.php
- resources/views/shipments/index.blade.php
- resources/views/shipments/requests.blade.php
- resources/views/shipments/set.blade.php
- resources/views/shipments/track-shipment.blade.php
Multiple empty lines are a stylistic choice and should not be allowed as they could complicate merging. This disallows them.
> Formatting fix for Blade multiple empty lines

- app/Http/Controllers/ControlPanelController.php
- app/Http/Livewire/Groups/Edit.php
- app/Http/Livewire/Groups/Permissions/Edit.php
- app/Http/Livewire/Users.php
- app/Http/Livewire/Users/Edit.php
- app/Http/Livewire/Users/Roles/Edit.php
- app/Models/User.php
- app/Providers/AppServiceProvider.php
- resources/views/components/control-panel/sidebar.blade.php
- resources/views/control-panel/groups.blade.php
- resources/views/control-panel/groups/edit.blade.php
- resources/views/control-panel/info.blade.php
- resources/views/control-panel/users.blade.php
- resources/views/control-panel/users/edit.blade.php
- resources/views/layouts/navigation.blade.php
- resources/views/livewire/groups/edit.blade.php
- resources/views/livewire/groups/permissions/edit.blade.php
- resources/views/livewire/users.blade.php
- resources/views/livewire/users/edit.blade.php
- resources/views/livewire/users/roles/edit.blade.php
- routes/web.php
- Add user management.
- Add user role management.
- Add role management.
- Add role permission management.
> Add authorization management to control panel

- app/Http/Kernel.php
- app/Http/Middleware/LogUserActivity.php
- database/migrations/2023_04_13_193644_create_logs_table.php
logging user activity on website - for implementing project AI
> logUser activity website

- app/Models/User.php
- resources/views/profile/edit.blade.php
- resources/views/profile/partials/update-profile-information-form.blade.php
I have formated, tnx for notifying me
> Verify customer change

- app/Http/Controllers/ShipmentController.php
Bing Maps Locations API template added, to be used for shipment tracking.
- With the logic, addresses can be converted to geocodes(latitude, longitude) to be able to present a visual showcase of the shipment history to the relevant user(s).
> Bing Maps Locations API template added.

- resources/views/customers.blade.php
- resources/views/customers_edit.blade.php
> style searchbar customers

- resources/views/customers.blade.php
- resources/views/customers_edit.blade.php
Reverts Practice-Enterprise2/AD#75
> Revert "style searchbar customers"

- app/Models/User.php
- resources/views/profile/edit.blade.php
- resources/views/profile/partials/update-profile-information-form.blade.php
Reverts Practice-Enterprise2/AD#74
> Revert "Verify customer change"

- .prettierrc.yaml
- README.md
- database/README.md
- docs/authorization.md
- Add information on how to get started developing a new feature using a
fork, instead of working on the main branch
- Add information on how to create correct pull requests
- Update the information on how to setup and run the project
> Development documentation update

- resources/views/admin/users.blade.php
kleine aanpassing zodat admin zichzelf niet kunnen buiten sluiten :D
> locking niet voor admin

- app/Http/Controllers/ApiController.php
- app/Http/Controllers/ShipmentController.php
- app/Http/Controllers/WaypointController.php
- app/Http/Kernel.php
- app/Http/Livewire/Role/Create.php
- app/Notifications/ShipmentUpdated.php
- app/Policies/EmployeePolicy.php
- app/Traits/Invoices.php
- config/permission.php
- database/migrations/2023_03_01_145506_create_shipments_table.php
- database/migrations/2023_04_17_144007_create_dimensions_table.php
- pint.json
Update the Pint config to aggressively remove newlines. Be gone custom style.
> Laravel Pint config update and format

- app/Console/Kernel.php
- app/Http/Controllers/PayslipController.php
- composer.json
- composer.lock
- public/css/payslip.css
- resources/views/pdf/payslip.blade.php
* back to before pdf install
* after pdf install
* comment pdf install
* format
> Payslip rework

- app/Exceptions/Handler.php
- config/logging.php
update these fields in the .env :
APP_DEBUG=false
LOG_CHANNEL=custom_txt_log
> changed the error handeling

- routes/auth.php
- routes/web.php
Deleted unused function that caused some bugs
> Error response

- app/Http/Controllers/NotificationController.php
- app/Http/Controllers/ShipmentController.php
- app/Http/Controllers/WaypointController.php
- app/Notifications/ShipmentUpdated.php
- app/Providers/AppServiceProvider.php
- resources/views/components/navigation.blade.php
- resources/views/shipments/show.blade.php
- routes/web.php
Index page is only showing the user's shipment now. For employee and admin they can see every shipment.
In show (details) page users are not able to see the qr code anymore. 
On WaypointController I deleted the part for dd (debug) and duplicate code for notification because it was blocking the sending of the notification.
> fixes for index and show pages and waypoint qr notification

- app/Http/Controllers/EmployeeController.php
- app/Providers/AppServiceProvider.php
- resources/views/app.blade.php
- resources/views/components/employees/create.blade.php
- resources/views/review.blade.php
- resources/views/reviews/index.blade.php
HR can acces the routes to create an view employees now
reviews are changed to current use of it
employee add type of housnumber is now set to number
employee add error handling if something went wrong
> Smallchanges
